# Generated by Django 2.2.4 on 2019-09-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rubro', '0001_initial'),
        ('productos', '0002_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rubro.Rubro'),
            preserve_default=False,
        ),
    ]
