# Generated by Django 2.2.4 on 2019-09-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productos_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productosXrubro', to='rubro.Rubro'),
        ),
    ]
